/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        image: {
            name: 'Image', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storageRef: {
                    name: "storageRef",
                    type: "String",
                }, displayName: {
                    name: "displayName",
                    type: "String",
                    isOptional: true,
                }, width: {
                    name: "width",
                    type: "Int",
                }, height: {
                    name: "height",
                    type: "Int",
                }, size: {
                    name: "size",
                    type: "BigInt",
                }, userProfiles: {
                    name: "userProfiles",
                    type: "UserProfile",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'profilePhoto',
                }, labProfiles: {
                    name: "labProfiles",
                    type: "LabProfile",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'profilePhoto',
                }, contents: {
                    name: "contents",
                    type: "Content",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'thumbnail',
                }, modules: {
                    name: "modules",
                    type: "Module",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'thumbnail',
                }, classes: {
                    name: "classes",
                    type: "Class",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'thumbnail',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        video: {
            name: 'Video', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, storageRef: {
                    name: "storageRef",
                    type: "String",
                }, displayName: {
                    name: "displayName",
                    type: "String",
                    isOptional: true,
                }, durationMillis: {
                    name: "durationMillis",
                    type: "Int",
                }, width: {
                    name: "width",
                    type: "Int",
                    isOptional: true,
                }, height: {
                    name: "height",
                    type: "Int",
                    isOptional: true,
                }, size: {
                    name: "size",
                    type: "BigInt",
                }, previewForContent: {
                    name: "previewForContent",
                    type: "Content",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'previewVideo',
                }, previewForModule: {
                    name: "previewForModule",
                    type: "Module",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'previewVideo',
                }, classes: {
                    name: "classes",
                    type: "Class",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'video',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        user: {
            name: 'User', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, displayName: {
                    name: "displayName",
                    type: "String",
                    isOptional: true,
                }, profile: {
                    name: "profile",
                    type: "UserProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'user',
                }, labs: {
                    name: "labs",
                    type: "UserLabJoin",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, ownedLabs: {
                    name: "ownedLabs",
                    type: "Lab",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'owners',
                    isRelationOwner: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        userProfile: {
            name: 'UserProfile', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'profile',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, bio: {
                    name: "bio",
                    type: "String",
                    isOptional: true,
                }, instagram: {
                    name: "instagram",
                    type: "String",
                    isOptional: true,
                }, profilePhoto: {
                    name: "profilePhoto",
                    type: "Image",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'userProfiles',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "profilePhotoId" },
                }, profilePhotoId: {
                    name: "profilePhotoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'profilePhoto',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId: {
                    name: "userId",
                    fields: ["userId"]
                },
            },
        },
        lab: {
            name: 'Lab', fields: {
                published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, profile: {
                    name: "profile",
                    type: "LabProfile",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'lab',
                }, owners: {
                    name: "owners",
                    type: "User",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'ownedLabs',
                    isRelationOwner: true,
                }, community: {
                    name: "community",
                    type: "UserLabJoin",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'lab',
                }, roles: {
                    name: "roles",
                    type: "Role",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'lab',
                }, privileges: {
                    name: "privileges",
                    type: "Privilege",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'lab',
                }, content: {
                    name: "content",
                    type: "Content",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'lab',
                }, permissions: {
                    name: "permissions",
                    type: "LabPermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'lab',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        labProfile: {
            name: 'LabProfile', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'profile',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'lab',
                }, bio: {
                    name: "bio",
                    type: "String",
                    isOptional: true,
                }, instagram: {
                    name: "instagram",
                    type: "String",
                    isOptional: true,
                }, profilePhoto: {
                    name: "profilePhoto",
                    type: "Image",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'labProfiles',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "profilePhotoId" },
                }, profilePhotoId: {
                    name: "profilePhotoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'profilePhoto',
                }, slug: {
                    name: "slug",
                    type: "String",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, labId: {
                    name: "labId",
                    fields: ["labId"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        userLabJoin: {
            name: 'UserLabJoin', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'labs',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'user',
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'community',
                    isRelationOwner: true,
                    onDeleteAction: 'Restrict',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'lab',
                }, userLabRoles: {
                    name: "userLabRoles",
                    type: "UserLabRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'userLabJoin',
                },
            }, uniqueConstraints: {
                userLabJoinId: {
                    name: "userLabJoinId",
                    fields: ["userId", "labId"]
                },
            },
        },
        role: {
            name: 'Role', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, shortDescription: {
                    name: "shortDescription",
                    type: "String",
                    isOptional: true,
                }, longDescription: {
                    name: "longDescription",
                    type: "String",
                    isOptional: true,
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'lab',
                }, userLabRoles: {
                    name: "userLabRoles",
                    type: "UserLabRole",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, privileges: {
                    name: "privileges",
                    type: "RolePrivilegeJoin",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'role',
                }, public: {
                    name: "public",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, priority: {
                    name: "priority",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, isTeamRole: {
                    name: "isTeamRole",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, labId_id: {
                    name: "labId_id",
                    fields: ["labId", "id"]
                }, name_labId: {
                    name: "name_labId",
                    fields: ["name", "labId"]
                },
            },
        },
        userLabRole: {
            name: 'UserLabRole', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, userLabJoin: {
                    name: "userLabJoin",
                    type: "UserLabJoin",
                    isDataModel: true,
                    backLink: 'userLabRoles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "userId": "userId", "labId": "labId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'userLabJoin',
                }, labId: {
                    name: "labId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'userLabJoin',
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'userLabRoles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "labId": "labId", "id": "roleId" },
                }, roleId: {
                    name: "roleId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                userLabRoleId: {
                    name: "userLabRoleId",
                    fields: ["userId", "labId", "roleId"]
                },
            },
        },
        privilege: {
            name: 'Privilege', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, longDescription: {
                    name: "longDescription",
                    type: "String",
                    isOptional: true,
                }, shortDescription: {
                    name: "shortDescription",
                    type: "String",
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'privileges',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'lab',
                }, roles: {
                    name: "roles",
                    type: "RolePrivilegeJoin",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'privilege',
                }, labPermissions: {
                    name: "labPermissions",
                    type: "LabPermission",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'privileges',
                    isRelationOwner: true,
                }, public: {
                    name: "public",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name_labId: {
                    name: "name_labId",
                    fields: ["name", "labId"]
                },
            },
        },
        labPermission: {
            name: 'LabPermission', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'permissions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'lab',
                }, privileges: {
                    name: "privileges",
                    type: "Privilege",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'labPermissions',
                    isRelationOwner: true,
                }, type: {
                    name: "type",
                    type: "String",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name_labId: {
                    name: "name_labId",
                    fields: ["name", "labId"]
                },
            },
        },
        rolePrivilegeJoin: {
            name: 'RolePrivilegeJoin', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, role: {
                    name: "role",
                    type: "Role",
                    isDataModel: true,
                    backLink: 'privileges',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "roleId" },
                }, roleId: {
                    name: "roleId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'role',
                }, privilege: {
                    name: "privilege",
                    type: "Privilege",
                    isDataModel: true,
                    backLink: 'roles',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "privilegeId" },
                }, privilegeId: {
                    name: "privilegeId",
                    type: "String",
                    isId: true,
                    isForeignKey: true,
                    relationField: 'privilege',
                }, order: {
                    name: "order",
                    type: "Int",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                rolePrivilegeJoinId: {
                    name: "rolePrivilegeJoinId",
                    fields: ["roleId", "privilegeId"]
                },
            },
        },
        content: {
            name: 'Content', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, lab: {
                    name: "lab",
                    type: "Lab",
                    isDataModel: true,
                    backLink: 'content',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "labId" },
                }, labId: {
                    name: "labId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'lab',
                }, name: {
                    name: "name",
                    type: "String",
                }, shortDescription: {
                    name: "shortDescription",
                    type: "String",
                    isOptional: true,
                }, longDescription: {
                    name: "longDescription",
                    type: "String",
                    isOptional: true,
                }, thumbnail: {
                    name: "thumbnail",
                    type: "Image",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'contents',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "thumbnailId" },
                }, thumbnailId: {
                    name: "thumbnailId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'thumbnail',
                }, modules: {
                    name: "modules",
                    type: "Module",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'content',
                }, published: {
                    name: "published",
                    type: "Boolean",
                }, previewVideo: {
                    name: "previewVideo",
                    type: "Video",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'previewForContent',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "previewVideoId" },
                }, previewVideoId: {
                    name: "previewVideoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'previewVideo',
                }, order: {
                    name: "order",
                    type: "Int",
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, labId_order: {
                    name: "labId_order",
                    fields: ["labId", "order"]
                },
            },
        },
        module: {
            name: 'Module', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, shortDescription: {
                    name: "shortDescription",
                    type: "String",
                    isOptional: true,
                }, longDescription: {
                    name: "longDescription",
                    type: "String",
                    isOptional: true,
                }, thumbnail: {
                    name: "thumbnail",
                    type: "Image",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'modules',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "thumbnailId" },
                }, thumbnailId: {
                    name: "thumbnailId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'thumbnail',
                }, content: {
                    name: "content",
                    type: "Content",
                    isDataModel: true,
                    backLink: 'modules',
                    isRelationOwner: true,
                    onDeleteAction: 'Restrict',
                    foreignKeyMapping: { "id": "contentId" },
                }, contentId: {
                    name: "contentId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'content',
                }, classes: {
                    name: "classes",
                    type: "Class",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'module',
                }, order: {
                    name: "order",
                    type: "Int",
                }, published: {
                    name: "published",
                    type: "Boolean",
                }, category: {
                    name: "category",
                    type: "String",
                    isOptional: true,
                }, previewVideo: {
                    name: "previewVideo",
                    type: "Video",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'previewForModule',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "previewVideoId" },
                }, previewVideoId: {
                    name: "previewVideoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'previewVideo',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, order_category_contentId: {
                    name: "order_category_contentId",
                    fields: ["order", "category", "contentId"]
                },
            },
        },
        class: {
            name: 'Class', fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, shortDescription: {
                    name: "shortDescription",
                    type: "String",
                    isOptional: true,
                }, longDescription: {
                    name: "longDescription",
                    type: "String",
                    isOptional: true,
                }, thumbnail: {
                    name: "thumbnail",
                    type: "Image",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'classes',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "thumbnailId" },
                }, thumbnailId: {
                    name: "thumbnailId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'thumbnail',
                }, module: {
                    name: "module",
                    type: "Module",
                    isDataModel: true,
                    backLink: 'classes',
                    isRelationOwner: true,
                    onDeleteAction: 'Restrict',
                    foreignKeyMapping: { "id": "moduleId" },
                }, moduleId: {
                    name: "moduleId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'module',
                }, order: {
                    name: "order",
                    type: "Int",
                }, published: {
                    name: "published",
                    type: "Boolean",
                }, video: {
                    name: "video",
                    type: "Video",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'classes',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "videoId" },
                }, videoId: {
                    name: "videoId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'video',
                }, category: {
                    name: "category",
                    type: "String",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, order_category_moduleId: {
                    name: "order_category_moduleId",
                    fields: ["order", "category", "moduleId"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['UserProfile', 'UserLabJoin'],
        lab: ['LabProfile', 'Role', 'Privilege', 'LabPermission', 'Content'],
        userLabJoin: ['UserLabRole'],
        role: ['UserLabRole', 'RolePrivilegeJoin'],
        privilege: ['RolePrivilegeJoin'],

    },
    authModel: 'User'

};
export default metadata;
