/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

export * from './image';
export * from './video';
export * from './user';
export * from './user-profile';
export * from './lab';
export * from './lab-profile';
export * from './user-lab-join';
export * from './role';
export * from './user-lab-role';
export * from './privilege';
export * from './lab-permission';
export * from './role-privilege-join';
export * from './content';
export * from './module';
export * from './class';
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5';
export { Provider } from '@zenstackhq/tanstack-query/runtime-v5/react';
export { default as metadata } from './__model_meta';
